# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ 1.15.2, 1.14.4, 1.16.3 ]
  pull_request:
    branches: [ 1.15.2 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      
    - name: Display build number
      run: echo Carpet TIS Addition Build \#$GITHUB_RUN_NUMBER
    - name: Set build number in code
      run: sed -i "s/build.undefined/build.$GITHUB_RUN_NUMBER/g" src/main/java/carpettisaddition/CarpetTISAdditionServer.java gradle.properties
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - uses: actions/upload-artifact@v2
      with:
        name: build.$GITHUB_RUN_NUMBER-artifacts
        path: build/libs/
